/**
 * Módulo Renderizador del Mapa Curricular (Super Panel 1 Sub Panel 1)
 * Renderiza dinámicamente el mapa de materias conectando las notas y el estado de cursada firmada.
 */

function renderizadorMapaCurricular() {
  renderizarMapaCurricular();
}

function renderizarMapaCurricular() {
  const contenedor = document.getElementById('sp1p1');
  if (!contenedor) return;

  const datos = window.datosGlobales?.datosAlumno || {};
  const aprobadas = datos.materiasAprobadas || [];
  const enCurso = datos.materiasEnCurso || [];

  const getMateriaInfo = (id) => aprobadas.find(m => m.id === id) || enCurso.find(m => m.id === id);

  const getGradeBadge = (id, fallbackNota = '–', fallbackCls = 'ag-green') => {
    const mat = getMateriaInfo(id);
    if (!mat) return `<span class="acc-grade ag-muted">–</span>`;
    if (mat.estado === 'firmada' || mat.modalidad === 'final_pendiente') {
      return `<span class="acc-grade ag-blue" title="Cursada Firmada / Rinde Examen Final">✍️</span>`;
    }
    if (mat.nota !== null && mat.nota !== undefined && mat.nota !== '') {
      return `<span class="acc-grade ag-green">${mat.nota}</span>`;
    }
    if (mat.modalidad && (mat.modalidad.startsWith('equivalencia') || mat.modalidad === 'equivalencia')) {
      return `<span class="acc-grade ag-equiv">✓</span>`;
    }
    if (enCurso.some(m => m.id === id)) {
      return `<span class="acc-grade ag-blue">${fallbackNota}</span>`;
    }
    return `<span class="acc-grade ${fallbackCls}">${fallbackNota}</span>`;
  };

  contenedor.innerHTML = `
    <div class="infobox" style="margin-bottom:16px;">
      <strong>Mapa Curricular K23:</strong> Hacé clic en cualquier tarjeta para ver su desglose o presioná <strong>✏️ Editar</strong>.
    </div>

    <div class="map-legend">
      <div class="ml-item"><span style="font-size:13px">🎓</span> Req. ADUSI</div>
      <div class="ml-item"><div class="ml-box" style="border-color:var(--green);background:rgba(34,211,164,.05)"></div> Aprobada K23</div>
      <div class="ml-item"><div class="ml-box" style="border-color:var(--blue);background:rgba(56,189,248,.05)"></div> En curso / Firmada (✍️)</div>
      <div class="ml-item"><div class="ml-box" style="border-color:var(--yellow);background:rgba(250,204,21,.08)"></div> Homologada K08 → K23</div>
      <div class="ml-item"><div class="ml-box" style="border-color:var(--pending-border);background:var(--pending-bg)"></div> Pendiente</div>
    </div>

    <div class="map-wrap">
      <div class="map-grid">
        <!-- NIVEL 1 -->
        <div class="map-col">
          <div class="map-lvl">Nivel 1 · 8/8 🎓</div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Análisis Matemático I <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('232001', '8')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">AM I (950702)</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232001', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Álgebra y Geometría Analítica <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-final">Final K08</span></div></div>${getGradeBadge('232002', '9')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Álgebra (950701)</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232002', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Física I <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-equiv">Equiv. Parcial + Tópicos</span></div></div>${getGradeBadge('232003', '✓')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen</span><span class="acc-row-val">Pase Carrera Anterior + Tópicos</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232003', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Inglés I <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('232004', '10')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Inglés Técnico I</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232004', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Lógica y Estructuras Discretas <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('232010', '9')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Matemática Discreta</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232010', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Algoritmos y Estructuras de Datos <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('082021', '10')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Algoritmos (082021)</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('082021', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Arquitectura de Computadoras <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('082022', '8')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Arquitectura de Computadores</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('082022', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Sistemas y Procesos de Negocio <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('232011', '8')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Sistemas y Orgs.</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232011', event)">✏️ Editar</button></div></div></div>
        </div>

        <!-- NIVEL 2 -->
        <div class="map-col">
          <div class="map-lvl">Nivel 2 · 8/8 🎓</div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Análisis Matemático II <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('232009', '9')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">AM II</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232009', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Física II <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('232010_f2', '9')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Física II</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232010_f2', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Ingeniería y Sociedad <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-equiv">Homologada K08</span></div></div>${getGradeBadge('232011_is', '✓')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Ingeniería y Sociedad</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232011_is', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Inglés II <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('232012', '9')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Inglés Técnico II</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232012', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Sintaxis y Semántica de Lenguajes <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('082025', '8')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Sintaxis y Semántica</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('082025', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Paradigmas de Programación <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('082026', '8')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Paradigmas de Programación</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('082026', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Sistemas Operativos <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-final">Final K08</span></div></div>${getGradeBadge('082027', '7')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Sistemas Operativos</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('082027', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Análisis de Sistemas de Info. <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('082024', '9')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Análisis de Sistemas</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('082024', event)">✏️ Editar</button></div></div></div>
        </div>

        <!-- NIVEL 3 + BLOQUE COMBINADO 3er/4to NIVEL -->
        <div class="map-col">
          <div class="map-lvl">Nivel 3 · 8/8 🎓 + Electivas</div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Probabilidad y Estadística <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('232017', '9')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Probabilidades y Estadísticas</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232017', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Economía <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-final">Final K08</span></div></div>${getGradeBadge('232018', '7')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Economía</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232018', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Bases de Datos <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('232030', '10')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Gestión de Datos</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232030', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Desarrollo de Software <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-plan">Directo K23</span></div></div>${getGradeBadge('232020', '✓')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Plan de Cursado</span><span class="acc-row-val">Plan K23 (Acreditada 02/03/2026)</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232020', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-pl" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Comunicación de Datos <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-plan">Directo K23</span></div></div>${getGradeBadge('232032', '1C', 'ag-blue')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Plan de Cursado</span><span class="acc-row-val">Plan K23 (En curso 1C 2026)</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-pri" style="padding:3px 8px;font-size:11px;margin-right:6px;background:var(--blue);color:#000;border:none;border-radius:4px;cursor:pointer;font-weight:600;" onclick="abrirMateria('materias/comunicacion-datos/index.html', 'Comunicación de Datos'); event.stopPropagation();">🔗 Ver Página</button><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232032', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Análisis Numérico <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-final">Final K08</span></div></div>${getGradeBadge('232033', '8')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Matemática Superior</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232033', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Diseño de Sistemas de Info. <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K08</span></div></div>${getGradeBadge('232034', '8')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Diseño de Sistemas</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232034', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Seminario de Integración <span class="badge-plan-k23">K23</span>🎓</div><div class="acc-badges"><span class="acc-badge ab-promo">Promoción K23</span></div></div>${getGradeBadge('082099', '9')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Plan de Cursado</span><span class="acc-row-val">Plan K23 Directo</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-pri" style="padding:3px 8px;font-size:11px;margin-right:6px;background:var(--blue);color:#000;border:none;border-radius:4px;cursor:pointer;font-weight:600;" onclick="abrirMateria('materias/seminario-integrador/index.html', 'Seminario de Integración'); event.stopPropagation();">🔗 Ver Página</button><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('082099', event)">✏️ Editar</button></div></div></div>
          
          <!-- Electivas Imputadas al Bloque 3º/4º -->
          <div class="acc-card s-ap" style="border-left-color:var(--yellow);" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Gestión del Talento Humano <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-promo">Electiva K08 Promocionada</span></div></div>${getGradeBadge('082117', '10')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Gestión del Talento Humano (082117)</span></div><div class="acc-row"><span class="acc-row-lbl">Acreditación</span><span class="acc-row-val">80hs Reloj · Bloque 3.º/4.º</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('082117', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" style="border-left-color:var(--yellow);" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Transformación Digital <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-promo">Electiva K08 Promocionada</span></div></div>${getGradeBadge('082102', '9')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Transformación Digital (082102)</span></div><div class="acc-row"><span class="acc-row-lbl">Acreditación</span><span class="acc-row-val">80hs Reloj · Bloque 3.º/4.º</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('082102', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" style="border-left-color:var(--yellow);" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Química (Acred. K08 → K23) <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-equiv">Acreditación K08 (Res. 3120/22)</span></div></div>${getGradeBadge('082091', '✓')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Química (081420)</span></div><div class="acc-row"><span class="acc-row-lbl">Acreditación</span><span class="acc-row-val">72hs Reloj al Bloque 3.º/4.º</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('082091', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-ap" style="border-left-color:var(--yellow);" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Sistemas de Representación <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-equiv">Acreditación K08 (Res. 3120/22)</span></div></div>${getGradeBadge('082092', '9')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Origen K08</span><span class="acc-row-val">Sistemas de Representación (951601)</span></div><div class="acc-row"><span class="acc-row-lbl">Acreditación</span><span class="acc-row-val">72hs Reloj al Bloque 3.º/4.º</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('082092', event)">✏️ Editar</button></div></div></div>
        </div>

        <!-- NIVEL 4 -->
        <div class="map-col">
          <div class="map-lvl">Nivel 4 · 1/6</div>
          <div class="acc-card s-pl" onclick="toggleAcc(this)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Adm. Sistemas de Información <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-anual">Anual K23</span></div></div>${getGradeBadge('232045', '26', 'ag-blue')}</div><div class="acc-body"><div class="acc-row"><span class="acc-row-lbl">Plan de Cursado</span><span class="acc-row-val">Plan K23 (En curso Anual 2026)</span></div><div class="acc-row" style="border:none;justify-content:flex-end;margin-top:6px;"><button class="btn-pri" style="padding:3px 8px;font-size:11px;margin-right:6px;background:var(--blue);color:#000;border:none;border-radius:4px;cursor:pointer;font-weight:600;" onclick="abrirMateria('materias/administracion-sistemas/index.html', 'Adm. de Sistemas de Información'); event.stopPropagation();">🔗 Ver Página</button><button class="btn-sec" style="padding:3px 8px;font-size:11px;" onclick="abrirModalEditarMateria('232045', event)">✏️ Editar</button></div></div></div>
          <div class="acc-card s-pe" onclick="abrirModalEditarMateria('232024', event)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Legislación <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-pend">2C 2026</span></div></div>${getGradeBadge('232024', '–')}</div></div>
          <div class="acc-card s-pe" onclick="abrirModalEditarMateria('082038', event)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Ingeniería y Calidad de Software <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-pend">2C 2026</span></div></div>${getGradeBadge('082038', '–')}</div></div>
          <div class="acc-card s-pe" onclick="abrirModalEditarMateria('232044', event)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Tecnologías Automatización <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-pend">2C 2026</span></div></div>${getGradeBadge('232044', '–')}</div></div>
          <div class="acc-card s-pe" onclick="abrirModalEditarMateria('232041', event)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Redes de Datos <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-pend">1C 2027</span></div></div>${getGradeBadge('232041', '–')}</div></div>
          <div class="acc-card s-pe" onclick="abrirModalEditarMateria('232043', event)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Simulación <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-pend">1C 2027</span></div></div>${getGradeBadge('232043', '–')}</div></div>
          
          <button class="btn-sec" style="width:100%;margin-top:10px;padding:6px;font-size:11.5px;border:1px dashed var(--blue);color:var(--blue);" onclick="abrirModalElectiva(4)">➕ Agregar Electiva (Bloque 3.º/4.º)</button>
        </div>

        <!-- NIVEL 5 & BLOQUE ESPECIALIZACIÓN -->
        <div class="map-col">
          <div class="map-lvl">Nivel 5 · Obligatorias + Electivas 5.º</div>
          <div class="acc-card s-pe" onclick="abrirModalEditarMateria('232051', event)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Inteligencia Artificial <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-pend">1C 2027</span></div></div>${getGradeBadge('232051', '–')}</div></div>
          <div class="acc-card s-pe" onclick="abrirModalEditarMateria('232052', event)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Ciencia de Datos <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-pend">2C 2027</span></div></div>${getGradeBadge('232052', '–')}</div></div>
          <div class="acc-card s-pe" onclick="abrirModalEditarMateria('232053', event)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Sistemas de Gestión <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-pend">2C 2027</span></div></div>${getGradeBadge('232053', '–')}</div></div>
          <div class="acc-card s-pe" onclick="abrirModalEditarMateria('232054', event)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Gestión Gerencial <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-pend">2C 2027</span></div></div>${getGradeBadge('232054', '–')}</div></div>
          <div class="acc-card s-pe" onclick="abrirModalEditarMateria('232055', event)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Seguridad en los Sistemas <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-pend">1C 2028</span></div></div>${getGradeBadge('232055', '–')}</div></div>
          <div class="acc-card s-pe" onclick="abrirModalEditarMateria('082037', event)"><div class="acc-header"><span class="acc-chevron">▶</span><div style="flex:1"><div class="acc-name">Proyecto Final <span class="badge-plan-k23">K23</span></div><div class="acc-badges"><span class="acc-badge ab-pend">2028-2029</span></div></div>${getGradeBadge('082037', '–')}</div></div>
          
          <button class="btn-sec" style="width:100%;margin-top:10px;padding:6px;font-size:11.5px;border:1px dashed var(--yellow);color:var(--yellow);" onclick="abrirModalElectiva(5)">➕ Agregar Electiva (Bloque 5.º Nivel)</button>
        </div>
      </div>
    </div>
  `;
}
